/**
 * Frases de placeholder para o textarea de criação de post.
 * Exibidas aleatoriamente ao abrir a página de criação.
 */
const POST_PLACEHOLDER_PHRASES = [
  'Hum, conta? já contou suas mentiras hoje?',
  'O que aconteceu? Cadê sua bola de cristal?',
  'Conta aí? tá pronta pro chá?',
  'Hum? Quer saber tudo ou só o suco do drama?',
  'O que rolou? Vai anotar no diário ou só pra threadr?',
  'Conta o que aconteceu? Com pipoca ou resumão?',
  'Hum, explica? Tá de terno pra interrogatório?',
  'O que aconteceu? Quer o trailer ou o filme inteiro?',
  'Conta? Assina o termo de confidencialidade primeiro',
  'Hum? Um buraco negro de thread, né gata',
  'O que rolou? Vai espalhar no grupo ou guardar pra você? Egoista',
  'Conta o que aconteceu? Pode ser narrativa épica?',
  'Hum? Tá gravando pro podcast das queridas?',
  'O que aconteceu? Quer spoilers ou surpresa?',
  'Conta? Versão sem censura',
  'Hum, explica aí? É pesquisa de campo ou só tédio?',
  'O que rolou? Vai julgar ou só fingir empatia?',
  'Conta o que aconteceu? Rápido ou com trilha sonora?',
  'Hum? Sua antena de thread tá ligada já?',
  'O que aconteceu? Quero o porquê e o escândalo',
  'Conta? Em código Morse ou português?',
  'Hum? Tá de microfone pra entrevista exclusiva?',
  'O que rolou? Versão família ou melhores amigos?',
  'Conta o que aconteceu? Ou vou ter que jogar no maps?',
  'Hum? Curiosidade matou o gato, hein?',
  'O que aconteceu? Vai postar isso no status?',
  'Conta? Com intervalo pra perguntas ou direto?',
  'Hum, explica? É revelação ou confissão anônima?',
  'O que rolou? Quero o antes, durante e depois',
  'Conta o que aconteceu? Pagando mico de graça de novo?',
  'Hum, conta? Tá com tempo livre ou só fingindo interesse?',
  'O que aconteceu? Quer o script completo ou improviso?',
  'Conta aí? É pra terapia coletiva ou solo?',
  'Hum? Cê marca hora pra thread?',
  'O que rolou? Com legendas ou dublagem?',
  'Conta o que aconteceu? Quero fimagem',
  'Hum, explica? Tá com bloco de notas pronto?',
  'O que aconteceu? Spoiler ou mistério?',
  'Conta? Com efeitos especiais ou cara limpa?',
  'Hum? Curiosidade nível stalker heim',
  'O que rolou? Vai compartilhar no stories ou privado?',
  'Conta o que aconteceu? Tá lerda heim',
  'Hum? É live ou replay do drama?',
  'O que aconteceu? Drama de herói e vilão?',
  'Conta? Em poesia ou prosa?',
  'Hum, explica aí? Tá cobrando entrada pro show de vergonha?',
  'O que rolou? Tem trilha sonora épica?',
  'Conta o que aconteceu Betinha?',
  'Hum? Seu radar de bisbilhotice grita né',
  'O que aconteceu? Direto ao ponto ou rodeios?',
  'Conta? Com memes ou chata?',
  'Hum? É interrogatório policial amigão?',
  'O que rolou? Pra rir ou pra chorar?',
  'Conta o que aconteceu? Haja tempo heim',
  'Hum? Tá de lupa pra detalhes minúciosos?',
  'O que aconteceu? Historinha ou fato consumado?',
  'Conta? Solo ou com plateia?',
  'Hum, explica? É aula ou papo de bar?',
  'O que rolou? Tá perdida colega?',
  'Conta o que aconteceu? Com final feliz garantido?',
];

/**
 * Frases de rate limit para posts (20 minutos de espera).
 * Exibidas quando o usuário tenta postar antes do cooldown.
 */
const POST_RATE_LIMIT_PHRASES = [
  'Ai, desculpa, 10 minutos de espera. Café enquanto isso?',
  'Cerca de 10 min? Pode sentar, tem Netflix no tédio.',
  'Desculpa aí, 10 minutinhos. Quer um biscoito anti-fome?',
  'Ai, espera 10 min. Vou cronometrar com amor.',
  'Cerca de 10? Relaxa, é tempo pra repensar a vida.',
  'Desculpa, mas 10 min de fila. Música de elevador pra animar?',
  'Ai, 10 minutos? Perfeito pra um cochilo rápido.',
  'Cerca de 10? Tá bom, levo água gelada pro suor.',
  'Desculpa, espera aí uns 10. Quer ler meu manual de paciência?',
  'Ai, 10 min? Vou te passar pro próximo nível de tédio.',
  'Cerca de 10 minutos? Ótimo, sobra pra scrollar o feed.',
  'Desculpa, mas 10 min. Tem wi-fi grátis no purgatório.',
  'Ai, espera 10? Vou te contar piada pra passar rápido.',
  'Cerca de 10? Senta que lá vem história da minha tia.',
  'Desculpa aí, 10 minutinhos. Quer chá ou cafeína?',
  'Ai, 10 min de espera? Clássico nosso, né amor?',
  'Cerca de 10? Relaxa, é meditação forçada.',
  'Desculpa, mas 10 min. Vou te dar upgrade pro VIP da espera.',
  'Ai, espera uns 10? Tempo pra eu admirar sua paciência.',
  'Cerca de 10 minutos? Perfeito pra playlist de sofrimento.',
  'Desculpa, 10 min aí. Quer selfie no balcão?',
  'Ai, 10 minutos? Vou te passar enigma pra distrair.',
  'Cerca de 10? Tá bom, levo ventilador pro calor da raiva.',
  'Desculpa aí, espera 10. História real: piorou pra outros.',
  'Ai, 10 min? Clássico hit do nosso repertório.',
  'Cerca de 10 minutos? Senta, tem podcast de reclamações.',
  'Desculpa, mas 10 min. Quer autógrafo meu?',
  'Ai, espera 10? Vou te dar troco em sorrisos falsos.',
  'Cerca de 10? Ótimo pra yoga de respiração profunda.',
  'Desculpa, 10 minutinhos. Próximo round: mais 10?',
  'Ai, desculpa, 10 min de espera. Quer cardápio de paciência?',
  'Cerca de 10? Senta aí, tem travesseiro pro suspiro.',
  'Desculpa aí, uns 10 minutos. Música ambiente de suspense?',
  'Ai, espera 10? Vou te dar like na sua tolerância.',
  'Cerca de 10 min? Perfeito pra maratona mental.',
  'Desculpa, mas 10 minutos. Wi-fi senha: seja paciente.',
  'Ai, 10 min? Clássico nosso, edição limitada.',
  'Cerca de 10? Relaxa, é spa de tédio incluso.',
  'Desculpa aí, espera 10. Quer horóscopo da fila?',
  'Ai, 10 minutos? Vou cronometrar com aplausos.',
  'Cerca de 10 min? Ótimo pra autoanálise grátis.',
  'Desculpa, uns 10. Tem chiclete anti-estresse?',
  'Ai, espera 10? História engraçada: o de ontem esperou 40.',
  'Cerca de 10 minutos? Senta que tem show de mágica lenta.',
  'Desculpa aí, 10 min. Upgrade: fila VIP com vista.',
  'Ai, 10 minutos? Playlist exclusiva de elevador.',
  'Cerca de 10? Vou te passar trivia pra passar o tempo.',
  'Desculpa, mas 10 min. Quer foto pro Insta da espera?',
  'Ai, espera uns 10? Medalha de ouro em paciência pro você.',
  'Cerca de 10 minutos? Tempo pra eu te hipnotizar.',
  'Desculpa aí, 10 min. Café cortesia no próximo atraso.',
  'Ai, 10 minutos? Clássico remix 2026.',
  'Cerca de 10? Relaxa, é terapia de grupo improvisada.',
  'Desculpa, espera 10. Quer assinar petição anti-filas?',
  'Ai, 10 min? Vou te contar segredo: piora depois.',
  'Cerca de 10 minutos? Perfeito pra bingo de desculpas.',
  'Desculpa aí, uns 10. Tem ventilador pro calor da espera?',
  'Ai, espera 10? Like se você aguentar!',
  'Cerca de 10 min? Spa day com cheiro de burocracia.',
  'Desculpa, 10 minutos. Próximo: bônus de 10 min grátis?',
];

/**
 * Frases de rate limit para respostas (15 minutos de espera).
 * Exibidas quando o usuário tenta responder antes do cooldown.
 */
const REPLY_RATE_LIMIT_PHRASES = [
  'Ai, desculpa, 15 min de espera. Quer um café expresso pra viagem?',
  'Cerca de 15? Senta, tem relógio no celular?',
  'Desculpa aí, uns 15 minutos. Quer água benta pra paciência?',
  'Ai, espera 15? Vou te dar uma estrelinha de bom comportamento.',
  'Cerca de 15 min? Perfeito pra um café rápido.',
  'Desculpa, mas 15 minutos. Wi-fi: pacienciabr.',
  'Ai, 15 min? Modo turbo do nosso hit.',
  'Cerca de 15? Relaxa, é aquecimento pro principal.',
  'Desculpa aí, espera 15. Trivia: qual a raiz de espera?',
  'Ai, 15 minutos? Cronômetro com confete no final.',
  'Cerca de 15 min? Tempo pra like no seu esforço.',
  'Desculpa, uns 15. Chiclete incluso no pacote.',
  'Ai, espera 15? Piada rápida: por que a fila é eterna?',
  'Cerca de 15 minutos? Spa express com essência de fila.',
  'Desculpa aí, 15 min. Foto pro sobrevivi?',
  'Ai, 15 minutos? Medalha prata em tolerância.',
  'Cerca de 15? Playlist curta de suspense.',
  'Desculpa, espera 15. Enigma: quanto é 15 min reais?',
  'Ai, 15 min? Café cortesia se chorar.',
  'Cerca de 15 minutos? Bingo rápido de desculpas.',
  'Desculpa aí, uns 15. Ventilador pro calorzinho.',
  'Ai, espera 15? Like se sobreviver!',
  'Cerca de 15 min? Terapia flash grátis.',
  'Desculpa, 15 minutos. Petição anti-15min?',
  'Ai, 15 min? Segredo: às vezes vira 25.',
  'Cerca de 15? Yoga express na cadeira.',
  'Desculpa aí, espera 15. Autógrafo meu?',
  'Ai, 15 minutos? Remix veloz do clássico.',
  'Cerca de 15 min? Horóscopo: paciência alta hoje.',
  'Desculpa, uns 15. Bônus: sorriso falso incluso.',
  'Ai, desculpa, 15 min. Timer com alarme motivacional?',
  'Cerca de 15? Senta que tem meme fresco.',
  'Desculpa aí, espera 15. Água gelada pro fogo?',
  'Ai, 15 minutos? Sticker ouro pra você.',
  'Cerca de 15 min? Scroll feed patrocinado.',
  'Desculpa, mas 15. Senha wi-fi: 15minhell.',
  'Ai, espera 15? Hit parade edição sprint.',
  'Cerca de 15? Aquecimento com pipoca virtual.',
  'Desculpa aí, 15 min. Quiz: adivinha o atraso?',
  'Ai, 15 minutos? Confete e aplausos no fim.',
  'Cerca de 15 min? Like duplo na paciência.',
  'Desculpa, uns 15. Bolinha anti-estresse?',
  'Ai, espera 15? Piada: fila é o novo esporte.',
  'Cerca de 15 minutos? Mini-spa de tédio.',
  'Desculpa aí, 15 min. Selfie com balcão?',
  'Ai, 15 minutos? Prata com brilho extra.',
  'Cerca de 15? Suspense em 15 batidas.',
  'Desculpa, espera 15. Charada temporal?',
  'Ai, 15 min? Chá express se reclamar.',
  'Cerca de 15 minutos? Bingo turbo pronto.',
  'Desculpa aí, uns 15. Ar-condicionado on.',
  'Ai, espera 15? Double like pro herói.',
  'Cerca de 15 min? Flash therapy agora.',
  'Desculpa, 15 minutos. Assina o abaixo-assinado?',
  'Ai, 15 min? Spoiler: melhora no 9.',
  'Cerca de 15? Respiração 4-7-8 inclusa.',
  'Desculpa aí, espera 15. Foto autografada?',
  'Ai, 15 minutos? Velocidade máxima deboche.',
  'Cerca de 15 min? Astro: fila favorável.',
  'Desculpa, uns 15. Prêmio: próximo é grátis!',
];

/** Retorna uma frase de placeholder aleatória para o textarea de post */
export function getRandomPlaceholderPhrase(): string {
  return POST_PLACEHOLDER_PHRASES[Math.floor(Math.random() * POST_PLACEHOLDER_PHRASES.length)];
}

/** Retorna uma frase de rate limit aleatória para posts (20 min) */
export function getRandomPostRatePhrase(): string {
  return POST_RATE_LIMIT_PHRASES[Math.floor(Math.random() * POST_RATE_LIMIT_PHRASES.length)];
}

/** Retorna uma frase de rate limit aleatória para respostas (30 min) */
export function getRandomReplyRatePhrase(): string {
  return REPLY_RATE_LIMIT_PHRASES[Math.floor(Math.random() * REPLY_RATE_LIMIT_PHRASES.length)];
}
